//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentPart2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchesTBL
    {
        public string TeamName { get; set; }
        public string OpponentName { get; set; }
        public string Result { get; set; }
        public string TeamTBLTeamName { get; set; }
    }
}
