//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerTBL
    {
        public string ManagerName { get; set; }
        public string ManagerNationality { get; set; }
        public string TeamName { get; set; }
    }
}
