//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAssignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PremFootballLeagueDBEntities : DbContext
    {
        public PremFootballLeagueDBEntities()
            : base("name=PremFootballLeagueDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ManagerTBL> ManagerTBLs { get; set; }
        public virtual DbSet<MatchesTBL> MatchesTBLs { get; set; }
        public virtual DbSet<PlayerTBL> PlayerTBLs { get; set; }
        public virtual DbSet<TeamTBL> TeamTBLs { get; set; }
    }
}
